// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUOzFwCU7Wlr01BkOutjNrgCdAk67jUlA',
    appId: '1:316983332927:web:819b8c23e9de4446f5688a',
    messagingSenderId: '316983332927',
    projectId: 'pulseadvi-addd4',
    authDomain: 'pulseadvi-addd4.firebaseapp.com',
    storageBucket: 'pulseadvi-addd4.firebasestorage.app',
    measurementId: 'G-W895D6Q0QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQrtqf8MX8PzCzYb68e4Px7OMPbP_fPRc',
    appId: '1:316983332927:android:543d25ff35fab422f5688a',
    messagingSenderId: '316983332927',
    projectId: 'pulseadvi-addd4',
    storageBucket: 'pulseadvi-addd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxp3_H7j8Te776kCnVoJqbubqhkFKggH4',
    appId: '1:316983332927:ios:6f912077e9d64cecf5688a',
    messagingSenderId: '316983332927',
    projectId: 'pulseadvi-addd4',
    storageBucket: 'pulseadvi-addd4.firebasestorage.app',
    iosBundleId: 'com.example.jobReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxp3_H7j8Te776kCnVoJqbubqhkFKggH4',
    appId: '1:316983332927:ios:6f912077e9d64cecf5688a',
    messagingSenderId: '316983332927',
    projectId: 'pulseadvi-addd4',
    storageBucket: 'pulseadvi-addd4.firebasestorage.app',
    iosBundleId: 'com.example.jobReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUOzFwCU7Wlr01BkOutjNrgCdAk67jUlA',
    appId: '1:316983332927:web:885473d5243c2f6af5688a',
    messagingSenderId: '316983332927',
    projectId: 'pulseadvi-addd4',
    authDomain: 'pulseadvi-addd4.firebaseapp.com',
    storageBucket: 'pulseadvi-addd4.firebasestorage.app',
    measurementId: 'G-CLSSJ82RZJ',
  );
}
